In [22]:
import numpy as np
import pandas as pd


### NUMPY

#### 1D- One Dimentional Arrays

In [23]:
arr = np.array([4,6,7,8,9,10])
print(arr)
print(type(arr))

[ 4  6  7  8  9 10]
<class 'numpy.ndarray'>


In [24]:
list = [2,34,6,7,8]
print(type(list))
print(list)

<class 'list'>
[2, 34, 6, 7, 8]


- when adding two arrays together it adds coressponding array elements of both arrays

In [25]:
arr_1 = np.array([4,6,7,8,9,10])
arr_2 = np.array([3,4,6,2,8,13])

arr_3 = arr_1 + arr_2
print(arr_3)


[ 7 10 13 10 17 23]


In [26]:
arr_4 = arr_1 - arr_2
print(arr_4)

[ 1  2  1  6  1 -3]


In [27]:
arr_5 = arr_1 * arr_2
print(arr_5)

[ 12  24  42  16  72 130]


In [28]:
arr_6 = arr_2 / arr_1
print(arr_6)

[0.75       0.66666667 0.85714286 0.25       0.88888889 1.3       ]


- Numeric operations with Numpy (get the sum of elements)

In [29]:
arr_1 = np.array([4,6,7,8,9,10])
arr_2 = np.array([3,4,6,2,8,13])

sum_of_arrays = np.sum(arr_1 + arr_2)
print(sum_of_arrays)

avaerage = np.mean(arr_1 + arr_2)
print(avaerage)

print(np.min(arr_1))
print(np.max(arr_1))
print(np.sqrt(arr_2))

80
13.333333333333334
4
10
[1.73205081 2.         2.44948974 1.41421356 2.82842712 3.60555128]


#### 2D Arrays

In [30]:
arr = np.array([[1,2,4],[3,5,6]])
print(arr)

[[1 2 4]
 [3 5 6]]


In [31]:
# count of coulmns and rows
print(arr.shape)
# return a tuple
print(type(arr.shape))

(2, 3)
<class 'tuple'>


In [32]:
# Number of individual elements inside the array
print(arr.size)

6


In [33]:
# prints the dimension (2D array = 2 Dimensions)
print(arr.ndim)

2


### 3D Arrays

In [34]:
arr_3D = np.array([
    [[1,2],[3,5],[6,7]],
    [[6,8],[9,6],[11,12]],
    [[4,5],[6,4],[9,2]]
    ])

print(arr.ndim)

2


In [35]:
print(arr_3D)

[[[ 1  2]
  [ 3  5]
  [ 6  7]]

 [[ 6  8]
  [ 9  6]
  [11 12]]

 [[ 4  5]
  [ 6  4]
  [ 9  2]]]


In [36]:
print(type(arr_3D))

<class 'numpy.ndarray'>


### Array Indexing

In [37]:
arr = np.array([[1,2,4],[3,5,6]])
print(arr)

[[1 2 4]
 [3 5 6]]


In [38]:
print(arr[1][2])

6


In [39]:
arr_3D = np.array([
    [[1,2],[5,7],[9,8]],
    [[3,4],[6,8],[10,12]],
    [[11,13],[14,16],[18,20]]
    ])

- Print 14 using Indexing and Negative Indexing

In [40]:
print(arr_3D[2,1,0])
print(arr_3D[-1,-2,-2])

14
14


- Print 3 using Indexing and Negative Indexing

In [41]:
print(arr_3D[1,0,0])
print(arr_3D[-2,-3,-2])

3
3


In [46]:
array = np.array([10,20,15,18,14,26,30])

con = array > 15
print(con)

filtered_arr = array[con]
print(filtered_arr)

[False  True False  True False  True  True]
[20 18 26 30]


- after filtering gives you 1 dimension not 2

In [61]:
arr = np.array([
    [12,5,7,20],
    [3,15,8,2],
    [10,25,6,18],
    [4,11,30,9]
])
arr_1 = arr[((arr>10)|(arr<5)) &(arr != 15)]
print(arr_1)


[12 20  3  2 25 18  4 11 30]


#### Array Initiializing

In [72]:
arr = np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [74]:
arr = np.full((2,3,4),7)
print(arr)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [ ]:
arr = np.empty((3,4))
print(arr)

# result is filled with garbage values in the Memory

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
